### start main onboarding
POST http://localhost:8080/onboarding/process
Content-Type: application/json

{
  "person": {
    "firstName": "Albert",
    "secondName": "Einstein",
    "contact": {
      "mail": "albert.einstein@test.de",
      "phoneNumber": "4917843297854"
    },
    "birthday": "1990-05-17"
  },
  "monthIncome": 1000,
  "amountOfCreditCards": 1
}

### Send message to main process
POST http://localhost:8080/onboarding/process/27e4136d-525c-4881-96d0-71fad761a2bd/messages/person-authentication-completed
Content-Type: application/json

{
  "message": {
    "status": "SUCCESS"
  }
}